export enum CoreActionsEnum {
  CORE_GET_LANG = 'CORE_GET_LANG',
  CORE_SET_LANG = 'CORE_SET_LANG',

  CORE_GET_DOCS = 'CORE_GET_DOCS',
  CORE_SET_DOCS = 'CORE_SET_DOCS',
  CORE_SET_IS_LOADING_DOCS = 'CORE_SET_IS_LOADING_DOCS',

  CORE_SET_VISIBLE_MODAL = 'CORE_SET_VISIBLE_MODAL',
  CORE_REMOVE_VISIBLE_MODAL = 'CORE_REMOVE_VISIBLE_MODAL',

  CORE_SET_IS_NEED_2F_AUTH = 'CORE_SET_IS_NEED_2F_AUTH',
  CORE_SET_IS_AUTH_ERROR = 'CORE_SET_IS_AUTH_ERROR',
  CORE_SET_IS_2F_AUTH_ERROR = 'CORE_SET_IS_2F_AUTH_ERROR',

  CORE_SET_IS_LOADING_RESET_PASSWORD = 'CORE_SET_IS_LOADING_RESET_PASSWORD',
  CORE_SET_IS_RESET_PASSWORD_ERROR = 'CORE_SET_IS_RESET_PASSWORD_ERROR',

  CORE_GET_IS_SIDE_BAR_CLOSED = 'CORE_GET_IS_SIDE_BAR_CLOSED',
  CORE_SET_IS_SIDE_BAR_CLOSED = 'CORE_SET_IS_SIDE_BAR_CLOSED',
}
